# Generated by Django 2.1.4 on 2019-01-04 13:47

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6)),
                ('mobile_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('mobile_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('mobile_3', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('address_1', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
