# Generated by Django 2.1.4 on 2019-01-04 14:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='mobile_1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mobile_2',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mobile_3',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
